name: stactools-osc-hazard
channels:
  - conda-forge
dependencies:
  - stactools>=0.4.0
  - xstac
  - pystac
  - shapely
  - zarr
  - xarray
  - zarr
  - pip
  - pip:
    - hazard@git+https://github.com/os-climate/hazard.git